apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
data:
  named.conf: |
    http local {
        endpoints { "/dns-query"; };
    };

    key "ddns-key" {
      algorithm hmac-sha256;
      secret "UErh2WRGlvHPC4/RYhdzP040xeP/EgNccDFocBi+P4w=";
    };

    options {
      directory "/var/cache/bind";

      // Security: Disable recursion to act as Authoritative only
      recursion no;
      allow-transfer { none; }; // Disable zone transfers by default
      allow-query { any; };    // Allow the world to query your auth records

      // Port listening
      listen-on { any; };
      listen-on tls ephemeral { any; };
      listen-on tls ephemeral http local { any; };
      listen-on-v6 { none; };
    };

    // Logging configuration
    logging {
        # Channel 1: The Console (for kubectl logs)
        channel "console" {
            stderr;
            severity info;
            print-time yes;
            print-category yes;
            print-severity yes;
        };

        # Channel 2: The File (for persistence on the PVC)
        # Ensure /var/lib/bind/logs exists or point to a writable dir
        channel "file_log" {
            file "/var/log/bind/named.log" versions 3 size 10m;
            severity info;
            print-time yes;
            print-category yes;
            print-severity yes;
        };

        # Assign categories to both channels
        category default { "console"; "file_log"; };
        category queries { "console"; "file_log"; };
        category config  { "console"; "file_log"; };
    };

    zone "org1.com" {
        type master;
        file "/var/lib/bind/db.org1.com";
        allow-update { key "ddns-key"; }; # Only clients with this key can update
    };

    zone "org2.com" {
        type master;
        file "/var/lib/bind/db.org2.com";
        allow-update { key "ddns-key"; };
    };