apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-admin-route
spec:
  parentRefs:
    - name: ingress-gateway
      namespace: kgateway-system
  hostnames:
    - "sso.lab.local"
  rules:
    - matches:
      - path: { type: PathPrefix, value: "/" }
      backendRefs:
        - name: keycloak
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-public-route
spec:
  parentRefs:
    - name: ingress-gateway
      namespace: kgateway-system
  hostnames:
    - "sso.yahya-lab.com"
  rules:
    - matches:
      - path: { type: PathPrefix, value: "/admin" }
      filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: "access-blocked"
            statusCode: 302
      backendRefs:
        - name: keycloak
          port: 8080
    - matches:
      - path: { type: PathPrefix, value: "/" }
      backendRefs:
        - name: keycloak
          port: 8080
