apiVersion: apps/v1
kind: Deployment
metadata:
  name: poweradmin
  labels:
    app: poweradmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poweradmin
  template:
    metadata:
      labels:
        app: poweradmin
    spec:
      containers:
      - name: poweradmin
        image: poweradmin/poweradmin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PA_CREATE_ADMIN
          value: "1"
        - name: DB_TYPE
          value: "pgsql"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: host
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: password
        # - name: DNS_NS1
        #   value: "ns1.yourdomain.com"
        # - name: DNS_NS2
        #   value: "ns2.yourdomain.com"
        # - name: DNS_HOSTMASTER
        #   value: "hostmaster.yourdomain.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: poweradmin
spec:
  selector:
    app: poweradmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
