apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-local-config
data:
  local.conf: |
    gpgsql-host=${PDNS_GPGSQL_HOST}
    gpgsql-dbname=${PDNS_GPGSQL_DBNAME}
    gpgsql-user=${PDNS_GPGSQL_USER}
    gpgsql-password=${PDNS_GPGSQL_PASSWORD}
    gpgsql-dnssec=yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns
  template:
    metadata:
      labels:
        app: pdns
    spec:
      containers:
      - name: pdns
        image: localhost/pdns-auth-50:5.0.2_psql
        env:
        - name: PDNS_AUTH_API_KEY
          valueFrom:
            secretKeyRef:
              name: pdns-api-key
              key: api-key
        - name: PDNS_GPGSQL_HOST
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: host
        - name: PDNS_GPGSQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: dbname
        - name: PDNS_GPGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: username
        - name: PDNS_GPGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: password
        - name: PDNS_GPGSQL_SSLMODE
          value: "disable"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/powerdns/pdns.d/local.conf
          subPath: local.conf
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 8081
          name: api
      volumes:
      - name: config-volume
        configMap:
          name: pdns-local-config
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-service
spec:
  selector:
    app: pdns
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: api
      port: 8081
      targetPort: 8081
  type: ClusterIP
