apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns
  template:
    metadata:
      labels:
        app: pdns
    spec:
      containers:
      - name: pdns
        image: powerdns/pdns-auth-50:5.0.2
        env:
        - name: PDNS_LAUNCH
          value: "gpgsql"
        - name: PDNS_GPGSQL_HOST
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: host
        - name: PDNS_GPGSQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: dbname
        - name: PDNS_GPGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: username
        - name: PDNS_GPGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdns-database-app
              key: password
        - name: PDNS_GPGSQL_SSLMODE
          value: "disable"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: api
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: api
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 8081
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-service
spec:
  selector:
    app: pdns
  ports:
    - name: dns-udp
      port: 5353
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 5353
      protocol: TCP
      targetPort: 53
    - name: api
      port: 8081
      targetPort: 8081
  type: ClusterIP
