apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: lab-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "root-ca-secret"
        key: "tls.crt"
  target:
    configMap:
      key: "ca-certificates.crt"