---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgBmkqJZakSkWZ/6j7AxVGlcYI2aY8R74X5JZY+/z1Z4rcNuxb10w8ts3USBk8k62guAEBS4xZZz8DCrh80Dmfpm6bUmK2pdmW2ynDv8JO8x9ekO8wiDtzy9i281UZ/VuZFZjPmjxat0KVCEZuw//JskAdoAsVDRJj5RtYTYlmsq1lbounLwF55TDM+WHU1QUYoQmxJNVS0oBMg+yuJ9q3ZwDOKAWbk8CAEOVM7D94nIzj1JgyEis7Y8oqwXbF8WgyDMWLJn3CE/0qnzS57EVVzdVwFMB2S4sSIwmPr0rnEuIgW4MS/q33v2GgvszU1VS+HETfx72Ym3bXvaP1Qf0dBcZIMGovJVkYhrIUe/8rDIk1DbJP4IYpBL3GUROs6ki+G98lZDxBEiFQapg88fJ+xxcAwgnbDjlC4pSpCN/KBHz1k8fKc/7Ykof9POYiHbo3jjwz+/wLP0YMdY7fKehVxT/ES9HjrFFH4WwTQ9wz2egZRYadOMvY6bpaPl3oL6nn1PxZC350wUMNisVKWFDovJMX7kl/xEpPJ/RWTwSp6qe0Jnm1YzfUpZJuIDRZ0RHd3GyuycLubYyXR1amDkt5gOGQ+pH+ufuiOQO22s9hFzJoowBR16boXGAr3iZwK/gdyonWSiB+nEbGFvKhzXXpRnvgdgmj7tlG1NXHUlRjajmB+ihmHMeQj+alf7b9ROpiZkEC8pqC6+WvtT/u2zzxNT2DFNThNx/Lk6sL7NQyiixFoRQtvpbmIY6sheGHODrHLYDq0JrM2jiaUNLVizm9pYhx/SyKuVZGbMoXMb3GjYCn4ZmyyVtlBw/N3aC+lsA4lM00MzumwuKC8ZKmlXhRQd0Wz3cuAmLQQ2uXRPMvHbke2tLXGqTSUBgpbaiFdWwfav+vPyMDMGebn0Jscg1l3TP2hhzw9U3ZwzAVga44Xyn2nqzx4X5aBn
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflare-tunnel
