---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAdGvp8IsFSzOF3YPCxTHjiYBNTgOpUT7DA6DeCzaE5sWHzzIzxybHKd5LInGG25avXs5Qnnv5Q3UMTTncv4iV+CkHLxaVZoBQX4KJ7K+5UhA8ND0aloixtPB9SnFU/nAoIPraw5MogzLKLbjk/bMz+71WQVDBP1KpGzl8ARVzj7ols6UlBRvg/G2Fo3xcq+x7BMDwhehzuRJDGvKKLvpL5DhS4gWJYWUAG+rb2LkFFRa+aainYnxXaNGxs3t5e8Av7U2wczvKS4cGOcloLYSx34jRSMSYvaG7Tc4AKP+X5YXYvSRcHFkA8lkDjIPjG3xBlgFFaeU7ohUZ5TBHNMYb8zL2yXHfvlY3J4gHYwurewW6jPata0++VRsXymoi9EVrG3cH6AXIK6O8i5Y9xZe7sDxqlIG2GgWvKkN3KgLS7TLs4qcImR3mMQYkSlGu5c3wdqNWHpNNRIjAKMzh+KPd6B0UjbMs25yZiEmL5A7fBN6KeDegKfX4v5f60V4x6EQWv/7A86K6cBCeVMmWXLWRYonRoL2mr/RzTG87nXRt0nIecwS8evp72tnIvfWdTpVgtvI7VK0PDwMqHIagahuN4qWyJpQE4/nBEA/K9dxC33U97wQmi3iesb1ndt4ugabTeMtkW4lLQJBOENx4N16FdqH0RieJ0PSSottsCHyUaxVyXLVM0Tkl7RLeZ1cbd3sZPlZeO9eSDT2WZ9Ur0QBfz/IBIq1vSuk/Ow4CPLzisFffXaDNiTP639+53fAKmWUkrkZA6TkieMMm5SdQ5xbM0aD/v6q8fKT4AyST4VhBE2uJdabquA78CmsaBIZLYLp9iPwDJ6OrUVjK0mUj8jRmCh5kWszn9AFWFt7UCHdEyPYjFZnWg9Lo+IsBSN525kpVDSmMnAMgh80VravvnTeieBiCSTiMP0HFhQwutlUqjohm9Fxd74NhY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: tunnel-token
      namespace: cloudflare-tunnel