apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bind9
  namespace: argocd
spec:
  destination:
    namespace: bind9-system
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: platform/bind9
    repoURL: https://github.com/yahya-alshamrani/gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true