apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: powerdns
  namespace: argocd
spec:
  destination:
    namespace: powerdns-system
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: platform/powerDNS
    repoURL: https://github.com/yahya-alshamrani/gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true