apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staticDNS
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: platform/staticDNS
    repoURL: https://github.com/yahya-alshamrani/gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true