apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/trust-manager
    repoURL: https://github.com/yahya-alshamrani/gitops
    targetRevision: main
  ignoreDifferences: 
    - group: ""
      kind: Namespace
      name: cert-manager
      jsonPointers:
        - /metadata/labels/app.kubernetes.io~1managed-by
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true