apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: acme@yahya-lab.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: acme@yahya-lab.com
          apiTokenSecretRef:
            name: cloudflare-apikey-secret
            key: api-token
      selector:
        dnsZones:
        - 'yahya-lab.com'