apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik-user
  storage:
    size: 10Gi
  postgresql:
    parameters:
      password_encryption: 'scram-sha-256'
    pg_hba:
      - host authentik authentik-user all scram-sha-256
      - local all all trust
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"