apiVersion: v1
kind: Service
metadata:
  name: snappymail-service
  labels:
    app.kubernetes.io/name: snappymail
    app.kubernetes.io/instance: snappymail
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: snappymail
    app.kubernetes.io/instance: snappymail